sudo: false
language: ruby
cache: bundler
rvm:
  - 2.4.1
git:
  submodules: false
gemfile:
  - Gemfile
matrix:
  include:
    - rvm: 2.4.1
      gemfile: gemfiles/rubyracer
    - rvm: 2.4.1
      gemfile: gemfiles/alaska
      env: ALASKA=1
  allow_failures:
    - rvm: 2.4.1
      gemfile: gemfiles/alaska
      env: ALASKA=1
